version: '3'
services:
  bootnode:
    image: dlt-node
    container_name: bootnode
    hostname: bootnode
    volumes:
      - ./../config/dlt/bootnode.env:/dlt-network/.env
    command: ./bootnode_start.sh
    network_mode: "host"
    restart: always

  node1:
    image: dlt-node
    container_name: node1
    hostname: node1
    depends_on:
      - bootnode
    volumes:
      - ./../config/dlt/node1.env:/dlt-network/.env
      - ./../config/dlt/genesis/genesis_2_validators.json:/dlt-network/genesis.json
    command: ./node_start.sh
    network_mode: "host"
    restart: always

  eth-netstats:
    image: eth-netstats
    container_name: eth-netstats
    depends_on:
      - node1
    network_mode: "host"
    restart: always