networks:
  dlt_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
services:
  bootnode:
    command: ./bootnode_start.sh
    container_name: bootnode
    hostname: bootnode
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.4
    restart: always
    volumes:
    - ./local-env/bootnode.env:/dlt-network/.env
  grafana:
    container_name: grafana
    depends_on:
    - influxdb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: desire6g2024;
      GF_SECURITY_ADMIN_USER: desire6g
    image: grafana/grafana:latest
    networks:
      dlt_network:
        ipv4_address: 172.18.0.3
    ports:
    - 3000:3000
    restart: always
    volumes:
    - ./../grafana/datasources:/etc/grafana/provisioning/datasources
    - ./../grafana/dashboards:/etc/grafana/provisioning/dashboards
  influxdb:
    container_name: influxdb
    environment:
      INFLUXDB_DB: geth
      INFLUXDB_HTTP_AUTH_ENABLED: 'false'
      INFLUXDB_HTTP_FLUX_ENABLED: 'false'
    image: influxdb:1.8
    networks:
      dlt_network:
        ipv4_address: 172.18.0.2
    ports:
    - 8086:8086
    restart: always
  node1:
    command: ./node_start.sh
    container_name: node1
    depends_on:
    - bootnode
    hostname: node1
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.5
    restart: always
    volumes:
    - ./local-env/node1.env:/dlt-network/.env
    - ./../../config/dlt/genesis/genesis_5_validators.json:/dlt-network/genesis.json
  node2:
    command: ./node_start.sh
    container_name: node2
    depends_on:
    - bootnode
    hostname: node2
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.6
    restart: always
    volumes:
    - ./local-env/node2.env:/dlt-network/.env
    - ./../../config/dlt/genesis/genesis_5_validators.json:/dlt-network/genesis.json
  node3:
    command: ./node_start.sh
    container_name: node3
    depends_on:
    - bootnode
    hostname: node3
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.7
    restart: always
    volumes:
    - ./local-env/node3.env:/dlt-network/.env
    - ./../../config/dlt/genesis/genesis_5_validators.json:/dlt-network/genesis.json
  node4:
    command: ./node_start.sh
    container_name: node4
    depends_on:
    - bootnode
    hostname: node4
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.8
    restart: always
    volumes:
    - ./local-env/node4.env:/dlt-network/.env
    - ./../../config/dlt/genesis/genesis_5_validators.json:/dlt-network/genesis.json
  node5:
    command: ./node_start.sh
    container_name: node5
    depends_on:
    - bootnode
    hostname: node5
    image: dlt-node
    networks:
      dlt_network:
        ipv4_address: 172.18.0.9
    restart: always
    volumes:
    - ./local-env/node5.env:/dlt-network/.env
    - ./../../config/dlt/genesis/genesis_5_validators.json:/dlt-network/genesis.json
version: '3.7'
