apiVersion: v1
kind: Pod
metadata:
  name: ros-subscriber
spec:
  containers:
    - name: ros-subscriber
      image: ros-app
      imagePullPolicy: IfNotPresent
      env:
        - name: ROS_MASTER_URI
          value: "http://10.11.7.4:11311" 
        - name: ROS_IP
          value: "<ros_ip>"  # Replace <ros_ip> with the desired ROS IP address
        - name: ROS_ROLE
          value: "subscriber"          
        - name: ROS_TOPIC
          value: "chatter"
  hostNetwork: true
