apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: federation-net
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "vxlan200",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "10.0.0.0/16",
      "rangeStart": "10.0.1.2",
      "rangeEnd": "10.0.1.50"
    }
  }'
